services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    # Aqu√≠ es donde ocurre la magia de la portabilidad
    environment:
      - TOWER_IP=${TOWER_IP}
      - LAPTOP_IP=${LAPTOP_IP_WIFI} 
    ports:
      - "9090:9090"
    restart: unless-stopped
